version: '3'

services:
  server:
    build: ./server
    ports:
      - "1000:1000"
    environment:
      - MONGO_DB_URL=mongodb+srv://graphql:express@graphql-express.wvjpkdp.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
