name: Docker CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: hevkotaras/chat-deem-client-1:latest
          cache-from: type=local,src=/tmp/.buildx-cache-client
          cache-to: type=local,dest=/tmp/.buildx-cache-client

      - name: Image digest
        run: echo ${{ steps.docker_build_client.outputs.digest }}

      - name: Run container and test
        run: |
          docker run -d --name test_container -p 8080:80 hevkotaras/chat-deem-client-1:latest
          sleep 10
          curl http://localhost:8080

  server-build-and-test:
    needs: [client-build-and-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: hevkotaras/chat-deem-server-1:latest
          cache-from: type=local,src=/tmp/.buildx-cache-server
          cache-to: type=local,dest=/tmp/.buildx-cache-server

      - name: Image digest
        run: echo ${{ steps.docker_build_server.outputs.digest }}

      - name: Run container and test
        run: |
          docker run -d --name test_container -p 1000:1000 hevkotaras/chat-deem-server-1:latest
          sleep 10
          curl http://localhost:1000
