name: Docker CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Node install dependencies
        run: npm install

      - name: Run unit tests
        run: CI=true npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: hevkotaras/chat-deem-client-1:latest

      - name: Run container
        run: |
          docker run -d --name test_container -p 8080:80 hevkotaras/chat-deem-client-1:latest
          sleep 10
          docker logs test_container
          curl http://localhost:8080

  server-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Node install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: hevkotaras/chat-deem-server-1:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
      

      - name: Run container and test
        run: |
          docker run -d --name test_container -p 1000:1000 hevkotaras/chat-deem-server-1:latest
          sleep 10
          docker logs test_container
          curl http://localhost:1000
      
      
